In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

with open("math.txt", 'r', encoding='utf-8') as myfile:
    mytext = myfile.read()

In [3]:
mytokenizer = Tokenizer()
mytokenizer.fit_on_texts([mytext])
total_words = len(mytokenizer.word_index) + 1

In [4]:
mytokenizer.word_index

{'the': 1,
 'a': 2,
 'of': 3,
 'in': 4,
 'and': 5,
 'for': 6,
 'find': 7,
 'solve': 8,
 'area': 9,
 'calculate': 10,
 'an': 11,
 'given': 12,
 'determine': 13,
 'equation': 14,
 'involving': 15,
 'unknown': 16,
 'its': 17,
 'with': 18,
 'radius': 19,
 'using': 20,
 'volume': 21,
 'you': 22,
 'height': 23,
 'function': 24,
 'how': 25,
 'do': 26,
 'surface': 27,
 'terms': 28,
 'length': 29,
 'to': 30,
 'trigonometric': 31,
 'system': 32,
 'equations': 33,
 'square': 34,
 'is': 35,
 'what': 36,
 'two': 37,
 'known': 38,
 'circle': 39,
 'base': 40,
 'cone': 41,
 'roots': 42,
 'side': 43,
 'sum': 44,
 'both': 45,
 'logarithmic': 46,
 'triangle': 47,
 'perimeter': 48,
 'derivative': 49,
 'functions': 50,
 'formula': 51,
 'exponential': 52,
 'value': 53,
 'sphere': 54,
 'probability': 55,
 'line': 56,
 'quadratic': 57,
 'rational': 58,
 'between': 59,
 'variable': 60,
 'angle': 61,
 'by': 62,
 'compute': 63,
 '𝑛': 64,
 'n': 65,
 'linear': 66,
 'when': 67,
 'prism': 68,
 'rectangular': 69,
 'f

In [5]:
my_input_sequences = []
for line in mytext.split('\n'):
    token_list = mytokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        my_n_gram_sequence = token_list[:i+1]
        my_input_sequences.append(my_n_gram_sequence)

In [6]:
max_sequence_len = max([len(seq) for seq in my_input_sequences])
input_sequences = np.array(pad_sequences(my_input_sequences, maxlen=max_sequence_len, padding='pre'))

In [7]:
input_sequences[1]

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  7,
        1, 71], dtype=int32)

In [8]:
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [9]:
X[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 1], dtype=int32)

In [10]:
y

array([  1,  71,   3, ...,   2, 198, 205], dtype=int32)

In [11]:
y = np.array(tf.keras.utils.to_categorical(y, num_classes=total_words))

In [12]:
y[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [13]:
model = Sequential()
model.add(Embedding(total_words, 100, input_length=max_sequence_len-1))
model.add(LSTM(150))
model.add(Dense(total_words, activation='softmax'))
print(model.summary())

2024-12-01 17:31:07.351341: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2024-12-01 17:31:07.351374: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-12-01 17:31:07.351381: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-12-01 17:31:07.351628: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-12-01 17:31:07.352052: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 18, 100)           80100     
                                                                 
 lstm (LSTM)                 (None, 150)               150600    
                                                                 
 dense (Dense)               (None, 801)               120951    
                                                                 
Total params: 351651 (1.34 MB)
Trainable params: 351651 (1.34 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [14]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, y, epochs=100, verbose=1)

Epoch 1/100


2024-12-01 17:31:08.388320: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


426/426 [==============================] - 10s 21ms/step - loss: 4.2473 - accuracy: 0.2395
Epoch 2/100
426/426 [==============================] - 8s 19ms/step - loss: 3.0027 - accuracy: 0.4325
Epoch 3/100
426/426 [==============================] - 9s 21ms/step - loss: 2.4728 - accuracy: 0.4926
Epoch 4/100
426/426 [==============================] - 9s 21ms/step - loss: 2.1696 - accuracy: 0.5302
Epoch 5/100
426/426 [==============================] - 9s 20ms/step - loss: 1.9589 - accuracy: 0.5562
Epoch 6/100
426/426 [==============================] - 9s 21ms/step - loss: 1.7993 - accuracy: 0.5708
Epoch 7/100
426/426 [==============================] - 8s 20ms/step - loss: 1.6661 - accuracy: 0.5933
Epoch 8/100
426/426 [==============================] - 9s 22ms/step - loss: 1.5567 - accuracy: 0.6095
Epoch 9/100
426/426 [==============================] - 9s 20ms/step - loss: 1.4615 - accuracy: 0.6231
Epoch 10/100
426/426 [==============================] - 8s 20ms/step - loss: 1.3763 - accurac

In [29]:
input_text = "Find the volume of a cone with "
predict_next_words= 6

for _ in range(predict_next_words):
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[7, 1, 21, 3, 2, 41, 18]
1/1 [==============================] - 0s 16ms/step
[7, 1, 21, 3, 2, 41, 18, 2]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12]
1/1 [==============================] - 0s 16ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19]
1/1 [==============================] - 0s 13ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5]
1/1 [==============================] - 0s 14ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86]
1/1 [==============================] - 0s 14ms/step
Find the volume of a cone with  a given radius and slant height


In [39]:
input_text = "Find the volume of a cone with "
predict_next_words= 10

for _ in range(predict_next_words) :
    token_list = mytokenizer.texts_to_sequences([input_text])[0]
    print(token_list)
    token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in mytokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

[7, 1, 21, 3, 2, 41, 18]
1/1 [==============================] - 0s 16ms/step
[7, 1, 21, 3, 2, 41, 18, 2]
1/1 [==============================] - 0s 14ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12]
1/1 [==============================] - 0s 14ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86, 23]
1/1 [==============================] - 0s 16ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86, 23, 5]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86, 23, 5, 40]
1/1 [==============================] - 0s 15ms/step
[7, 1, 21, 3, 2, 41, 18, 2, 12, 19, 5, 86, 23, 5, 40, 19]
1/1 [==============================] - 0s 14ms/step
Find the volume of a cone with  a given radius and slant height and 